"""Database creation

Revision ID: ea6beab86875
Revises: 
Create Date: 2023-09-14 21:57:26.890798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea6beab86875'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_enter', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('puppet_id', sa.Integer(), nullable=True),
    sa.Column('chat_name', sa.String(), nullable=True),
    sa.Column('chat_telegram_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('chat_to_send_id', sa.Integer(), nullable=True),
    sa.Column('offset_num', sa.Integer(), nullable=True),
    sa.Column('message_hash', sa.String(), nullable=True),
    sa.Column('date_enter', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parser_pattern_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('block', sa.String(), nullable=True),
    sa.Column('ignore', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('puppets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('api_id', sa.String(), nullable=True),
    sa.Column('api_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('puppets')
    op.drop_table('parser_pattern_list')
    op.drop_table('messages')
    op.drop_table('chat_list')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
